spring:
  profiles:
    active: dev
  data:
    rest:
      base-path: /data-api
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
  rabbitmq:
    template:
      receive-timeout: 30000

---
spring:
  profiles: dev

---
spring:
  profiles: prod
  rabbitmq:
    host: rabbit.tacocloud.com
    port: 5673
    username: tacoweb
    password: l3tm31n
    exchange: tacocloud.order
    routing-key: kitchens.central