spring:
  data:
    rest:
      base-path: /data-api

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks

  artemis:
    host: localhost
    port: 61617
    user: username
    password: password

  jms:
    template:
      default-destination: tacocloud.order.queue